on: 
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "YouTube video to convert"
        required: true
      output_type:
        description: "mp3|mp4"
        default: "mp3"
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  convertVideo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv -p python mpthree
        ls -lah
        source mpthree/bin/activate
        python -m pip install --upgrade yt-dlp
        python -m pip list
        yt-dlp --version
        curl -OJL https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
        tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz
        ls -lah ffmpeg-master-latest-linux64-gpl/bin
        mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg .
        chmod +x ffmpeg
        ./ffmpeg --version
        echo "downloading ${{ github.event.inputs.youtube_url }}"
        yt-dlp --extract-audio --audio-format mp3 ${{ github.event.inputs.youtube_url }} -o output.mp3
        ls -lah
        curl -F "file=@output.mp3" https://tmpfiles.org/api/v1/upload
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
