on: 
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "YouTube video to convert"
        required: true
      output_type:
        description: "mp3|mp4"
        default: "mp3"
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  convertVideo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv -p python mpthree
        source mpthree/bin/activate
        python -m pip install --upgrade yt-dlp
        python -m pip list
        yt-dlp --version
        curl -OJL https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
        tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz
        mv ffmpeg-master-latest-linux64-gpl/bin/ff* .
        chmod +x ffmpeg
        export PATH=${PWD}:$PATH
        echo "downloading ${{ github.event.inputs.youtube_url }}"
        yt-dlp --extract-audio --audio-format mp3 ${{ github.event.inputs.youtube_url }}
        ls -lah
        MP3FILE=$( ls | grep mp3 )
        echo "file name: $MP3FILE"
        
        curl -F "file=@${MP3FILE}" https://tmpfiles.org/api/v1/upload
  
