on: 
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "YouTube video to convert"
        required: true
      output_type:
        description: "mp3|mp4"
        default: "mp3"
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  convertVideo:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - run: |
        apt-get update &&         apt-get install -y youtube-dl
        echo "downloading ${{ github.event.inputs.youtube_url }}"
        youtube-dl --extract-audio --audio-format mp3 ${{ github.event.inputs.youtube_url }}
        ls -lah
        curl -F "file=@*.mp3" https://tmpfiles.org/api/v1/upload
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
